### PR TITLE
Fixes for ghc 8.4.3

### PR DESCRIPTION
**Pull request by tstat**
Add Semigroup instance for FieldMap
Allow doctest < 0.17

### CODE REVIEW

**Comment by mitchellwrosen** [comment]
Thanks, can you remove the `.nix` files from this PR?

**Comment by mitchellwrosen** [comment]
(I'm just not sure what to do with them, or how to keep them up to date :sweat:)

**Comment by tstat** [comment]
Sure, they are now removed.

**Comment by mitchellwrosen** [comment]
Thank you sir

**Pull request merged**
